IcingaFormDecorator: Don't wrap `SubmitElement` and `SubmitButtonElements
Icinga/ipl-web pull request #118
Opened 2023-02-27 18:41 UTC by TAINCER

closes #117

2023-03-01 11:45 UTC, nilmerg requested changes

2023-03-01 11:45 UTC, nilmerg commented on src/FormDecorator/IcingaFormDecorator.php
> +            $this->formElement instanceof SubmitButtonElement
There's the `FormSubmitElement` interface. Use it instead and the `if` doesn't need to be disassembled. You're introducing way to much noise in the change history with this litte change.

2023-03-06 08:26 UTC, lippserd reviewed
If I understand the change correctly, it does the following:

* It no longer creates an empty `div` for the **label** of submit elements. The submit element will still be wrapped.
* A wrapper `div` for the `legend` or an empty `div` is now created for `FieldsetElement`. 

If this is correct, please adjust commit message and description as well as PR title and description. As the current state does not reflect the actual change.

2023-03-06 08:58 UTC, TAINCER commented
> * It no longer creates an empty `div` for the **label** of submit elements. The submit element will still be wrapped.
Yes, primarily to fix the failing [CompatFormTest](https://github.com/Icinga/ipl-web/actions/runs/4254446866/jobs/7400709057#step:5:21).

> * A wrapper `div` for the `legend` or an empty `div` is now created for `FieldsetElement`.
No, I misunderstood the previous change request, this should remain as it was before.

2023-03-06 09:07 UTC, lippserd commented
> > * A wrapper `div` for the `legend` or an empty `div` is now created for `FieldsetElement`.
> 
> No, I misunderstood the previous change request, this should remain as it was before.

So this PR is not ready to review yet, correct?

2023-03-06 09:19 UTC, nilmerg approved these changes

2023-03-06 09:20 UTC, TAINCER commented
> > > * A wrapper `div` for the `legend` or an empty `div` is now created for `FieldsetElement`.
> > 
> > 
> > No, I misunderstood the previous change request, this should remain as it was before.
> 
> So this PR is not ready to review yet, correct?

It is now, sorry. Also, this should not create an empty div for the `SubmitButtonElements` and not remove them entirely. I updated the title for that.

2023-03-06 09:24 UTC, lippserd approved these changes

2023-03-06 09:38 UTC, merged