Add copy to clipboard button widget
Icinga/ipl-web pull request #151
Opened 2023-05-25 08:41 UTC by raviks789

The button copies the text from the specified target id when mentioned otherwise it copies the text from the parent element.

ref Icinga/icingadb-web#677

2023-05-30 08:00 UTC, nilmerg requested changes
This does not "resolve" the issue in Icinga DB Web. It refers to it at a maximum. Currently this looks like this: 
![image](https://github.com/Icinga/ipl-web/assets/16668527/03571792-2a49-409b-ac2a-112fe9a3c331)

* Please only show the button upon hover of the parent (The rule for this must be available here!)
* Please fade "Copied" out
* The button's outline is placed weird, has different spacing left and right

2023-06-01 14:03 UTC, nilmerg requested changes

2023-06-01 14:03 UTC, nilmerg commented on asset/js/widget/CopyToClipboard.js
> +                button.innerHTML = 'Copied';
Please fetch the label from a data attribute and translate it on the server.

2023-06-01 14:03 UTC, nilmerg commented on asset/js/widget/CopyToClipboard.js
> +
please remove that empty line

2023-06-12 07:06 UTC, nilmerg requested changes
I just noticed in the linked PR that we litter the markup with IDs for no real reason. The thing with IDs is that they are (need..) to be unique, but this uniqueness is not required here.

We already have a guaranteed wrapper. So why not use it as point of reference?

In the button's `parentElement` (which is assumed to be always the wrapper) we lookup a direct child with the attribute `data-clipboard-source` and use it as source.

No fallback needed. If it's not there, an error should be logged. (We have no source that has no id, at this time)

Anyone using `attachTo` doesn't need to adjust the element then in any way, the data-attribute can be set automatically.

2023-06-12 13:32 UTC, nilmerg requested changes

2023-06-12 13:32 UTC, nilmerg commented on src/Widget/CopyToClipboard.php
> +        }
Remove this, the id of the source should be not of interest. Add the attribute to the source instead.

2023-06-12 13:32 UTC, nilmerg commented on src/Widget/CopyToClipboard.php
> +        $this->setContent(new Icon('clone'));
setHtmlContent?

2023-06-12 13:32 UTC, nilmerg commented on src/Widget/CopyToClipboard.php
> +        return $clipboardWrapper;
Please set the wrapper really as wrapper and return void here.

2023-06-14 07:28 UTC, nilmerg requested changes
With the plan in mind to introduce the behavior for this in Icinga Web, the feature won't be available unless the user upgrades to the new release. The click on the button then has no effect. So please let the constructor of `CopyToClipboard.js` add a class that enables the hover/focus effect. And add a `tabindex=-1` by default to the button, which the constructor should also remove. This prevents the button from being reachable by keyboard.

2023-06-14 07:28 UTC, nilmerg commented on asset/css/copy-to-clipboard.less
> +    color: @control-color;
```suggestion
    color: var(--control-color, @control-color);
```

2023-06-15 09:37 UTC, flourish86 approved these changes
Fine from the design perspective.

2023-06-15 14:13 UTC, nilmerg commented on asset/js/widget/CopyToClipboard.js
> +                            button.classList.remove('persistent');
Having two classes for this is somehow redundant. Use only one please.

2023-06-19 08:40 UTC, nilmerg requested changes

2023-06-20 09:56 UTC, nilmerg approved these changes

2023-06-20 09:57 UTC, merged