balls.less: Remove unused color property from `.ball-outline()`
Icinga/ipl-web pull request #156
Opened 2023-06-05 12:54 UTC by sukhwinder33445

2023-06-15 07:34 UTC, nilmerg commented
This applies to all icons with just an outline. i.e. ok, up and pending. @flourish86 Is it ok that it applies to pending states?

2023-06-15 08:15 UTC, flourish86 commented
> This applies to all icons with just an outline. i.e. ok, up and pending. @flourish86 Is it ok that it applies to pending states?

Yes. 😊

2023-06-15 08:15 UTC, flourish86 approved these changes

2023-06-19 07:31 UTC, nilmerg requested changes
Please change the Commit/PR description. It's not *unused*.

2023-06-19 08:12 UTC, merged