Integrate list and table widgets from Icinga DB Web
Icinga/ipl-web pull request #183
Opened 2023-08-09 12:30 UTC by yhabteab

2023-08-25 12:37 UTC, sukhwinder33445 requested changes
Please commit new changes separately.

2023-08-28 12:45 UTC, sukhwinder33445 reviewed
Please commit the changes from 627d7aa separately.

2023-09-07 08:50 UTC, sukhwinder33445 requested changes
Please add the requested changes in https://github.com/Icinga/icingadb-web/pull/830.

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseItemList.php
> +     * @param iterable<object> $data Data source of the list
Same here.

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseItemTable.php
> +     * @param iterable<object> $data Data source of the table
Same here.

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseItemList.php
> +    protected $data;
As described in the constructor, `$data` can also be an array.

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseItemTable.php
>      protected $data;
As described in the constructor, `$data` can also be an array.

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseTableRowItem.php
> +    protected function createVisual()
Is there a reason why you have not defined the return type here?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseTableRowItem.php
> +    protected function assemble()
and here?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Widget/ShowMore.php
> +    protected function assemble()
Return type?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Widget/Notice.php
> +    protected function assemble()
Return type?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Widget/EmptyState.php
> +    protected function assemble()
Return type?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseStatusBar.php
> +    protected function assemble()
Return type please?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseOrderedListItem.php
> +    public function getOrder()
Return type please?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseOrderedItemList.php
> +    protected function assemble()
Return type please?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseListItem.php
> +    protected function assemble()
Return type please?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseListItem.php
> +    protected function createVisual()
Return type please?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseItemTable.php
> +    protected function assemble()
Return type please?

2023-09-07 08:50 UTC, sukhwinder33445 commented on src/Common/BaseItemList.php
> +    protected function assemble()
Return type please?

2023-09-07 11:38 UTC, sukhwinder33445 requested changes

2023-09-07 11:38 UTC, sukhwinder33445 commented on src/Common/BaseOrderedListItem.php
> +     */
Please add `@throws`.

2023-09-07 11:38 UTC, sukhwinder33445 commented on src/Common/BaseOrderedListItem.php
> +    protected $order;
Not set via constructor, so use `@var ?int`.

2023-09-08 13:22 UTC, nilmerg submitted a review, later dismissed

2023-09-08 13:50 UTC, nilmerg approved these changes

2023-09-08 14:16 UTC, merged