Add tool tip to control items without label
Icinga/ipl-web pull request #25
Opened 2021-06-14 10:28 UTC by raviks789

Tool tip to LimitControl and SortControl is added to provide additional information to the user.

icinga/icingadb-web#144

2021-06-14 14:33 UTC, flourish86 requested changes

2021-06-14 14:33 UTC, flourish86 commented on src/Control/LimitControl.php
> +            'title'   => sprintf('Change item count per page'),
I think you should use the `t(…)` function for translation. You also don't need `sprintf()`, since you don't replace anything.

2021-06-14 14:33 UTC, flourish86 commented on src/Control/SortControl.php
> +            'title' => sprintf('Change sort direction'),
Same here.

2021-06-16 10:06 UTC, nilmerg approved these changes

2021-06-16 10:07 UTC, merged